### ISSUE TITLE
Form Error Handling

### ISSUE THREAD

**Issue by tuppers360** [HamedBahram/next-multistep-form#2]
Hi, wonderful implementation for the multi step form, however is there a way of removing the error state for each field when updating them to a valid state and also to display an error message if the field is an error after being updated? 

It appears that as the buttons are outside the scope of the form the error handling is not as elegant as it would be if the whole form was on the page.

Putting the button inside the form cause all the elements to be validated and therefore future steps show errors as they haven't been filled

My thought would be that to achieve this an individual form would be required for each step?

**Comment by HamedBahram** [comment]
Different ways you can improve this. You can pass the `mode: "onChange"` to your `useForm` hook to watch the inputs. You can also have individual forms for each step with a global state holding all data.

**Comment by tuppers360** [comment]
thanks for replying, I have looked at the mode but it is documented that this could really impact on performance so I guess it would depend on the complexity of the form. Will have to play around with it a little to see.

Again great work, your videos are really useful and really help.
