### ISSUE TITLE
Calling react-hook-form trigger method manually disables automatic re-validation on onChange

### ISSUE THREAD

**Issue by samislam** [HamedBahram/next-multistep-form#3]
Hi. I was following your tutorial, and I faced the following issue. 

This is a simplified version of the actual multistep form I was building following [the YouTube](https://www.youtube.com/watch?v=lW_0InDuejU) tutorial.

I have the following code:
```tsx
import { z } from 'zod'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { Button, Container, FormControl, FormHelperText, Stack, TextField } from '@mui/material'

const demoSchema = z.object({
  fieldA: z.string().min(2),
})

type DemoFields = z.infer<typeof demoSchema>

function App() {
  const {
    watch,
    trigger,
    register,
    formState: { errors },
  } = useForm<DemoFields>({ resolver: zodResolver(demoSchema) })

  const submitHandler = (data: DemoFields) => console.log(data)

  const alt = async () => {
    const isOk = await trigger('fieldA')
    console.log(isOk)
    if (isOk) submitHandler(watch())
  }

  return (
    <Container>
      <Stack>
        <FormControl error={!!errors.fieldA}>
          <TextField label="Username" {...register('fieldA')} />
          <FormHelperText>{errors.fieldA?.message}</FormHelperText>
        </FormControl>
        <Button onClick={alt} variant="contained">
          Submit!
        </Button>
        <pre>{watch('fieldA')}</pre>
      </Stack>
    </Container>
  )
}

export default App
```

If I write "h" in the input field, and then I click on the "Submit!" button, of course I see a validation error, and the error message gets print on the screen:

[![enter image description here][1]][1]

This is good. however, the normal behavior of react-hook-form now is I have to click on the "Submit!" button again to get rid of the red error message.

+ Is using `trigger()` makes everything from now on manual? is that documented anywhere? 

+ I want the normal react-hook-form behavior to happen, so that when I write inside the input field, the error goes away as I type correctly. 

Here's a [preview][2] in stack bilitz (*if you're using brave browser, turn off the shields*).

  [1]: https://i.stack.imgur.com/aMTgr.png
  [2]: https://stackblitz.com/edit/stackblitz-starters-yq4gab?file=src%2FApp.tsx

Question asked on StackOverflow [here](https://stackoverflow.com/questions/77852239/calling-react-hook-form-trigger-method-manually-disables-automatic-re-validation) as well

**Comment by HamedBahram** [comment]
That's right, Islam! Calling the `trigger` function disables automatic revalidation, unless you pass the `mode="onChange"` to your `useForm()` hook.

**Comment by samislam** [comment]
Doing onChange will make validation show error immediately when user starts typing, even before submitting

**Comment by HamedBahram** [comment]
I can't think of any other way unless you create separate forms for each step, and merge the data into a global state. See the example from the docs here → https://react-hook-form.com/advanced-usage#WizardFormFunnel
